#!/usr/bin/env python3
"""BEM-933 active queue continuity guard.

This guard is deliberately operator-gated. It may repair inconsistent metadata
for existing runnable tasks, but it must never invent a new roadmap task on its
own. Empty/IDLE queues are valid when they explicitly require an operator gate.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

DEFAULT_QUEUE = Path("governance/roadmap/ACTIVE_QUEUE.json")
OPERATOR_GATE_TEXT = "Operator gate required before adding new scope."


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def is_operator_stop(queue: Dict[str, Any]) -> bool:
    marker = str(queue.get("operator_stop") or queue.get("closure_reason") or "").upper()
    return "OPERATOR_STOP" in marker or marker.strip() == "STOP"


def first_runnable_task(tasks: List[Dict[str, Any]]) -> Optional[str]:
    for status in ("IN_PROGRESS", "PENDING"):
        for task in tasks:
            if isinstance(task, dict) and task.get("status") == status and task.get("id"):
                return str(task["id"])
    return None


def has_operator_gate(queue: Dict[str, Any]) -> bool:
    if queue.get("operator_gate_required") is True:
        return True
    next_action = str(queue.get("next_action") or "")
    guard_status = str(queue.get("guard_status") or "")
    return "operator gate" in next_action.lower() or guard_status == "OPERATOR_GATE_REQUIRED"


def normalize_idle_gate(queue: Dict[str, Any], now: Optional[str] = None) -> Dict[str, Any]:
    """Normalize an empty queue into an explicit operator-gated IDLE state."""
    now = now or utc_now()
    repaired = json.loads(json.dumps(queue))
    repaired["queue_state"] = "IDLE"
    repaired["current_task"] = None
    repaired["operator_gate_required"] = True
    repaired["guard_status"] = "OPERATOR_GATE_REQUIRED"
    repaired["next_action"] = OPERATOR_GATE_TEXT
    repaired["updated_at"] = now
    return repaired


def repair_queue(queue: Dict[str, Any], now: Optional[str] = None) -> Dict[str, Any]:
    """Repair queue metadata without autonomous scope creation.

    If a runnable task already exists, the guard may point current_task to it.
    If no runnable task exists, the only allowed repair is an explicit IDLE
    operator gate. Autogenerated BEM933-AUTO-NEXT tasks are forbidden.
    """
    now = now or utc_now()
    repaired = json.loads(json.dumps(queue))
    tasks = repaired.setdefault("tasks", [])

    if is_operator_stop(repaired):
        repaired["guard_status"] = "EXPLICIT_OPERATOR_STOP_RESPECTED"
        repaired["queue_state"] = repaired.get("queue_state") or "IDLE"
        repaired["current_task"] = None
        repaired["operator_gate_required"] = True
        repaired["next_action"] = "STOP respected. Operator gate required before any new scope."
        repaired["updated_at"] = now
        return repaired

    active_id = first_runnable_task(tasks)
    if active_id:
        repaired["queue_state"] = "ACTIVE"
        repaired["current_task"] = active_id
        repaired["operator_gate_required"] = False
        repaired["guard_status"] = "ACTIVE_QUEUE_GUARDED"
        repaired["next_action"] = f"{active_id} — continue existing roadmap task"
        repaired["updated_at"] = now
        return repaired

    return normalize_idle_gate(repaired, now)


def validate(queue: Dict[str, Any]) -> Dict[str, Any]:
    tasks = queue.get("tasks", [])
    current = queue.get("current_task")
    task_ids = {str(t.get("id")) for t in tasks if isinstance(t, dict)}
    runnable = first_runnable_task(tasks)
    problems: List[str] = []

    if is_operator_stop(queue):
        return {
            "status": "PASS",
            "mode": "operator_stop",
            "problems": [],
            "current_task": current,
            "task_count": len(tasks),
            "operator_gate_required": True,
        }

    if runnable:
        if queue.get("queue_state") != "ACTIVE":
            problems.append("queue_state_not_active_with_runnable_task")
        if not current:
            problems.append("current_task_empty_with_runnable_task")
        if current and current not in task_ids:
            problems.append("current_task_not_in_tasks")
    else:
        if queue.get("queue_state") not in ("IDLE", "CLOSED"):
            problems.append("empty_queue_not_idle_or_closed")
        if current:
            problems.append("current_task_set_without_runnable_task")
        if not has_operator_gate(queue):
            problems.append("empty_queue_without_operator_gate")

    return {
        "status": "PASS" if not problems else "FAIL",
        "mode": "active_task" if runnable else "operator_gate",
        "problems": problems,
        "current_task": current,
        "task_count": len(tasks),
        "runnable_task": runnable,
        "operator_gate_required": not bool(runnable),
        "autogenerated_task_creation": "FORBIDDEN",
    }


def smoke() -> Dict[str, Any]:
    closed = {"version": 1, "queue_state": "CLOSED", "current_task": None, "tasks": []}
    repaired = repair_queue(closed, "2026-06-16T18:55:00Z")
    result = validate(repaired)
    assert result["status"] == "PASS", result
    assert repaired["queue_state"] == "IDLE", repaired
    assert repaired["current_task"] is None, repaired
    assert repaired["operator_gate_required"] is True, repaired
    assert not any(str(t.get("id", "")).startswith("BEM933-AUTO-NEXT-") for t in repaired["tasks"]), repaired

    with_task = {
        "version": 1,
        "queue_state": "IDLE",
        "current_task": None,
        "tasks": [{"id": "BEM933-OPERATOR-APPROVED", "status": "PENDING"}],
    }
    repaired_task = repair_queue(with_task, "2026-06-16T18:55:00Z")
    task_result = validate(repaired_task)
    assert task_result["status"] == "PASS", task_result
    assert repaired_task["queue_state"] == "ACTIVE", repaired_task
    assert repaired_task["current_task"] == "BEM933-OPERATOR-APPROVED", repaired_task

    explicit_stop = repair_queue({"queue_state": "CLOSED", "operator_stop": "STOP", "tasks": []})
    assert explicit_stop["guard_status"] == "EXPLICIT_OPERATOR_STOP_RESPECTED", explicit_stop

    return {
        "status": "PASS",
        "checks": [
            "empty_queue_becomes_operator_gate_not_autotask",
            "existing_runnable_task_is_selected",
            "operator_stop_respected",
        ],
        "autogenerated_task_creation": "FORBIDDEN",
        "sample_empty_queue_state": repaired["queue_state"],
        "sample_current_task": repaired["current_task"],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Guard ACTIVE_QUEUE continuity with explicit operator gate")
    parser.add_argument("--queue", default=str(DEFAULT_QUEUE))
    parser.add_argument("--repair", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--smoke", action="store_true")
    args = parser.parse_args()

    if args.smoke:
        print(json.dumps(smoke(), indent=2, ensure_ascii=False))
        return

    path = Path(args.queue)
    queue = load_json(path)
    if args.repair:
        queue = repair_queue(queue)
        write_json(path, queue)

    result = validate(queue)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    if args.check and result["status"] != "PASS":
        raise SystemExit(1)


if __name__ == "__main__":
    main()
