#!/usr/bin/env python3
"""BEM-933 active queue continuity guard.

The guard prevents the roadmap from becoming inert after a release.  It is safe
for repo-side automation because it only edits ACTIVE_QUEUE.json and only when
there is no explicit operator stop.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

DEFAULT_QUEUE = Path("governance/roadmap/ACTIVE_QUEUE.json")


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, data: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def is_operator_stop(queue: Dict[str, Any]) -> bool:
    marker = str(queue.get("operator_stop") or queue.get("closure_reason") or "").upper()
    return "OPERATOR_STOP" in marker or marker.strip() == "STOP"


def first_active_task(tasks: List[Dict[str, Any]]) -> Optional[str]:
    for status in ("IN_PROGRESS", "PENDING"):
        for task in tasks:
            if task.get("status") == status and task.get("id"):
                return str(task["id"])
    return None


def generated_task(now: str) -> Dict[str, Any]:
    stamp = now.replace("-", "").replace(":", "").replace("T", "_").replace("Z", "")
    return {
        "id": f"BEM933-AUTO-NEXT-{stamp}",
        "title": "Autogenerated continuity task after empty queue",
        "status": "PENDING",
        "priority": 900,
        "source": "active_queue_guard",
        "acceptance": [
            "Replace autogenerated task with a concrete roadmap item",
            "Keep ACTIVE_QUEUE current_task non-null"
        ],
    }


def repair_queue(queue: Dict[str, Any], now: Optional[str] = None) -> Dict[str, Any]:
    now = now or utc_now()
    repaired = json.loads(json.dumps(queue))
    tasks = repaired.setdefault("tasks", [])

    if is_operator_stop(repaired):
        repaired["guard_status"] = "EXPLICIT_OPERATOR_STOP_RESPECTED"
        return repaired

    active_id = first_active_task(tasks)
    if active_id is None:
        tasks.append(generated_task(now))
        active_id = first_active_task(tasks)

    repaired["queue_state"] = "ACTIVE"
    repaired["current_task"] = active_id
    repaired["updated_at"] = now
    repaired["guard_status"] = "ACTIVE_QUEUE_GUARDED"
    repaired["next_action"] = f"{active_id} — continue autonomous development"
    return repaired


def validate(queue: Dict[str, Any]) -> Dict[str, Any]:
    tasks = queue.get("tasks", [])
    current = queue.get("current_taskb)
    task_ids = {str(t.get("id")) for t in tasks if isinstance(t, dict)}
    problems = []
    if queue.get("queue_state") != "ACTIVE":
        problems.append("queue_state_not_active")
    if not current:
        problems.append("current_task_empty")
    if current and current not in task_ids:
        problems.append("current_task_not_in_tasks")
    if not any(t.get("status") in ("IN_PROGRESS", "PENDING") for t in tasks if isinstance(t, dict)):
        problems.append("no_runnable_task")
    return {
        "status": "PASS" if not problems else "FAIL",
        "problems": problems,
        "current_task": current,
        "task_count": len(tasks),
    }


def smoke() -> Dict[str, Any]:
    closed = {"version": 1, "queue_state": "CLOSED", "current_task": None, "tasks": []}
    repaired = repair_queue(closed, "2026-06-15T18:41:00Z")
    result = validate(repaired)
    assert result["status"] == "PASS", result
    assert repaired["current_task"].startswith("BEM933-AUTO-NEXT-"), repaired
    explicit_stop = repair_queue({"queue_state": "CLOSED", "operator_stop": "STOP", "tasks": []})
    assert explicit_stop["guard_status"] == "EXPLICIT_OPERATOR_STOP_RESPECTED", explicit_stop
    return {
        "status": "PASS",
        "checks": ["closed_queue_repaired", "current_task_set", "operator_stop_respected"],
        "sample_current_task": repaired["current_task"],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Guard ACTIVE_QUEUE continuity")
    parser.add_argument("--queue", default=str(DEFAULT_QUEUE))
    parser.add_argument("--repair", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--smoke", action="store_true")
    args = parser.parse_args()

    if args.smoke:
        print(json.dumps(smoke(), indent=2, ensure_ascii=False))
        return

    path = Path(args.queue)
    queue = load_json(path)
    if args.repair:
        queue = repair_queue(queue)
        write_json(path, queue)

    result = validate(queue)
    print(json.dumps(result, indent=2, ensure_ascii=False))
    if args.check and result["status"] != "PASS":
        raise SystemExit(1)


if __name__ == "__main__":
    main()
