name: Update Status Report

on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - name: Disabled
        run: |
          echo "BEM-288: update-status.yml disabled because it generated invalid YAML errors."
